name: CI

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install

      #- name: DATABASE_URL
      #  run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          echo "SECRET_KEY= chacja" >> .env

      - name: Debug .env contents
        run: cat .env 

      - name: Clear database
        run: poetry run python3 src/db_helper.py
      
      #- name: Clear database hiala
      #  run: poetry run python3 src/db_helper.py
      - name: Run robot tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: bash run_robot_tests.sh

      - name: Run pytest
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: poetry run pytest src/tests

      - name: Coverage
        run: poetry run coverage run --branch -m pytest
          
      - name: Pylint
        run: poetry run pylint src --fail-under=9

      - name: Coverage report
        run: poetry run coverage xml
      - name: Coverage report to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
